Proxy support and refactoring
Paraboly/angularjs-es6-component-boilerplate pull request #6
Opened 2020-04-13 20:30 UTC by SchemeSonic

- Update index.html to match parabol angularjs environment
- Remove all ui dependencies from package.json
- Add proxy support
- Add .env file support

2020-04-13 20:32 UTC, SchemeSonic commented on package.json
> -    "angular": "^1.7.8",
I remove everything and inject them from index.html, we can leave angularjs as a peer dependency maybe?

2020-04-13 20:38 UTC, SchemeSonic commented on lib/index.html
> +  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
I add bootstrap's latest version(flex-based) instead of bootstrap 3 which we are using in our platform, we can migrate to bootstrap 4 or we can use tailwindcss maybe ?

2020-04-14 06:32 UTC, SchemeSonic commented on package.json
> -    "angular": "^1.7.8",
I add latest version of angularjs as peer dependency, apperantly it is peer dependency c84735c

2020-04-14 12:48 UTC, kuraydev approved these changes

2020-04-14 12:48 UTC, WrathChaos commented on lib/index.html
> +  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
Maybe we can install them on npm not link based

2020-04-14 20:08 UTC, starikcetin requested changes

2020-04-14 20:08 UTC, starikcetin commented on lib/index.html
> +  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
I think any CSS framework dependency doesn't belong in here. After all, all components should be self-contained, they should be free to use any CSS framework they want.

2020-04-14 21:11 UTC, egemenokten approved these changes

2020-04-17 13:50 UTC, SchemeSonic commented on lib/index.html
> +  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
@WrathChaos  @starikcetin index.html refers to external platforms like metis and sbs and I think we should not create atomic components because angularjs is no future for us. For the atomic components we can go with stencilJS boilerplate. 

My suggestion is; we should use this boilerplate as a small sandbox environment to develop fast angularjs component like https://github.com/dev-paraboly/sbs-internal-control-bid

2020-04-20 06:50 UTC, SchemeSonic commented
@starikcetin waiting your comments here https://github.com/Paraboly/angularjs-es6-component-boilerplate/pull/6#discussion_r410235942

2020-04-20 11:11 UTC, starikcetin commented on lib/index.html
> +  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
Fair point.

2020-04-20 15:59 UTC, starikcetin approved these changes

2021-05-31 08:43 UTC, closed without merging